# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"1\n\x0b\x43\x61lcRequest\x12\x10\n\x08operand1\x18\x01 \x01(\x02\x12\x10\n\x08operand2\x18\x02 \x01(\x02\"!\n\x0f\x43\x61lcAddResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\"&\n\x14\x43\x61lcSubtractResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\"6\n\x12\x43\x61lcDivideResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\x12\x10\n\x08zero_div\x18\x02 \x01(\x08\"&\n\x14\x43\x61lcMultiplyResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\x32\xab\x02\n\x0b\x43\x61lcService\x12?\n\x07\x43\x61lcAdd\x12\x17.calculator.CalcRequest\x1a\x1b.calculator.CalcAddResponse\x12I\n\x0c\x43\x61lcSubtract\x12\x17.calculator.CalcRequest\x1a .calculator.CalcSubtractResponse\x12\x45\n\nCalcDivide\x12\x17.calculator.CalcRequest\x1a\x1e.calculator.CalcDivideResponse\x12I\n\x0c\x43\x61lcMultiply\x12\x17.calculator.CalcRequest\x1a .calculator.CalcMultiplyResponseB\x1dZ\x1brpc_function/calculator_rpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\033rpc_function/calculator_rpc'
  _globals['_CALCREQUEST']._serialized_start=32
  _globals['_CALCREQUEST']._serialized_end=81
  _globals['_CALCADDRESPONSE']._serialized_start=83
  _globals['_CALCADDRESPONSE']._serialized_end=116
  _globals['_CALCSUBTRACTRESPONSE']._serialized_start=118
  _globals['_CALCSUBTRACTRESPONSE']._serialized_end=156
  _globals['_CALCDIVIDERESPONSE']._serialized_start=158
  _globals['_CALCDIVIDERESPONSE']._serialized_end=212
  _globals['_CALCMULTIPLYRESPONSE']._serialized_start=214
  _globals['_CALCMULTIPLYRESPONSE']._serialized_end=252
  _globals['_CALCSERVICE']._serialized_start=255
  _globals['_CALCSERVICE']._serialized_end=554
# @@protoc_insertion_point(module_scope)
