// Code generated by protoc-gen-go. DO NOT EDIT.
// source: push_notifications/rpc-stream/notifications.proto

package rpc_stream

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NotificationsRequest struct {
	Notification_Name    string   `protobuf:"bytes,1,opt,name=Notification_Name,json=NotificationName,proto3" json:"Notification_Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationsRequest) Reset()         { *m = NotificationsRequest{} }
func (m *NotificationsRequest) String() string { return proto.CompactTextString(m) }
func (*NotificationsRequest) ProtoMessage()    {}
func (*NotificationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67badd72df960690, []int{0}
}

func (m *NotificationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationsRequest.Unmarshal(m, b)
}
func (m *NotificationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationsRequest.Marshal(b, m, deterministic)
}
func (m *NotificationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationsRequest.Merge(m, src)
}
func (m *NotificationsRequest) XXX_Size() int {
	return xxx_messageInfo_NotificationsRequest.Size(m)
}
func (m *NotificationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationsRequest proto.InternalMessageInfo

func (m *NotificationsRequest) GetNotification_Name() string {
	if m != nil {
		return m.Notification_Name
	}
	return ""
}

type FruitResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Calories             float32  `protobuf:"fixed32,2,opt,name=Calories,proto3" json:"Calories,omitempty"`
	Carbohydrates        float32  `protobuf:"fixed32,3,opt,name=Carbohydrates,proto3" json:"Carbohydrates,omitempty"`
	Fat                  float32  `protobuf:"fixed32,4,opt,name=Fat,proto3" json:"Fat,omitempty"`
	Protein              float32  `protobuf:"fixed32,5,opt,name=Protein,proto3" json:"Protein,omitempty"`
	Sugar                float32  `protobuf:"fixed32,6,opt,name=Sugar,proto3" json:"Sugar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FruitResponse) Reset()         { *m = FruitResponse{} }
func (m *FruitResponse) String() string { return proto.CompactTextString(m) }
func (*FruitResponse) ProtoMessage()    {}
func (*FruitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_67badd72df960690, []int{1}
}

func (m *FruitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FruitResponse.Unmarshal(m, b)
}
func (m *FruitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FruitResponse.Marshal(b, m, deterministic)
}
func (m *FruitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FruitResponse.Merge(m, src)
}
func (m *FruitResponse) XXX_Size() int {
	return xxx_messageInfo_FruitResponse.Size(m)
}
func (m *FruitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FruitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FruitResponse proto.InternalMessageInfo

func (m *FruitResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FruitResponse) GetCalories() float32 {
	if m != nil {
		return m.Calories
	}
	return 0
}

func (m *FruitResponse) GetCarbohydrates() float32 {
	if m != nil {
		return m.Carbohydrates
	}
	return 0
}

func (m *FruitResponse) GetFat() float32 {
	if m != nil {
		return m.Fat
	}
	return 0
}

func (m *FruitResponse) GetProtein() float32 {
	if m != nil {
		return m.Protein
	}
	return 0
}

func (m *FruitResponse) GetSugar() float32 {
	if m != nil {
		return m.Sugar
	}
	return 0
}

type UniversitiesResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Web_Pages            string   `protobuf:"bytes,2,opt,name=Web_Pages,json=WebPages,proto3" json:"Web_Pages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UniversitiesResponse) Reset()         { *m = UniversitiesResponse{} }
func (m *UniversitiesResponse) String() string { return proto.CompactTextString(m) }
func (*UniversitiesResponse) ProtoMessage()    {}
func (*UniversitiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_67badd72df960690, []int{2}
}

func (m *UniversitiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UniversitiesResponse.Unmarshal(m, b)
}
func (m *UniversitiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UniversitiesResponse.Marshal(b, m, deterministic)
}
func (m *UniversitiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UniversitiesResponse.Merge(m, src)
}
func (m *UniversitiesResponse) XXX_Size() int {
	return xxx_messageInfo_UniversitiesResponse.Size(m)
}
func (m *UniversitiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UniversitiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UniversitiesResponse proto.InternalMessageInfo

func (m *UniversitiesResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UniversitiesResponse) GetWeb_Pages() string {
	if m != nil {
		return m.Web_Pages
	}
	return ""
}

func init() {
	proto.RegisterType((*NotificationsRequest)(nil), "notifications.NotificationsRequest")
	proto.RegisterType((*FruitResponse)(nil), "notifications.FruitResponse")
	proto.RegisterType((*UniversitiesResponse)(nil), "notifications.UniversitiesResponse")
}

func init() {
	proto.RegisterFile("push_notifications/rpc-stream/notifications.proto", fileDescriptor_67badd72df960690)
}

var fileDescriptor_67badd72df960690 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x5d, 0x4b, 0x3a, 0x41,
	0x14, 0xc6, 0x19, 0xdf, 0xfe, 0x7a, 0x40, 0xf0, 0x7f, 0xf2, 0x62, 0xb2, 0x22, 0xb1, 0x2e, 0x84,
	0x48, 0xad, 0xbe, 0x41, 0x82, 0xdd, 0x89, 0xac, 0x84, 0xe0, 0x8d, 0xcc, 0x6e, 0xa7, 0x75, 0x20,
	0x77, 0xb6, 0x99, 0x59, 0xa1, 0x4f, 0xd4, 0x87, 0xea, 0xcb, 0x84, 0xd3, 0x0b, 0x3b, 0x8b, 0x78,
	0xd1, 0xdd, 0x79, 0x7e, 0xcf, 0x59, 0xf6, 0xe1, 0x99, 0x03, 0x37, 0x69, 0x66, 0xd6, 0xab, 0x44,
	0x59, 0xf9, 0x2c, 0x23, 0x61, 0xa5, 0x4a, 0xcc, 0x50, 0xa7, 0xd1, 0xb5, 0xb1, 0x9a, 0xc4, 0x66,
	0xe8, 0x19, 0x83, 0x54, 0x2b, 0xab, 0xb0, 0xe9, 0xc1, 0xde, 0x18, 0xda, 0xd3, 0x3c, 0x08, 0xe8,
	0x35, 0x23, 0x63, 0xf1, 0x0a, 0xfe, 0xe7, 0xf9, 0x6a, 0x2a, 0x36, 0xc4, 0x59, 0x97, 0xf5, 0x1b,
	0x41, 0x2b, 0x6f, 0xec, 0x78, 0xef, 0x9d, 0x41, 0x73, 0xa2, 0x33, 0x69, 0x03, 0x32, 0xa9, 0x4a,
	0x0c, 0x21, 0x42, 0x25, 0xf7, 0x85, 0x9b, 0xb1, 0x03, 0xf5, 0xb1, 0x78, 0x51, 0x5a, 0x92, 0xe1,
	0xa5, 0x2e, 0xeb, 0x97, 0x82, 0x5f, 0x8d, 0x97, 0xd0, 0x1c, 0x0b, 0x1d, 0xaa, 0xf5, 0xdb, 0x93,
	0x16, 0x96, 0x0c, 0x2f, 0xbb, 0x05, 0x1f, 0x62, 0x0b, 0xca, 0x13, 0x61, 0x79, 0xc5, 0x79, 0xbb,
	0x11, 0x39, 0xfc, 0x9b, 0x69, 0x65, 0x49, 0x26, 0xbc, 0xea, 0xe8, 0x8f, 0xc4, 0x36, 0x54, 0xe7,
	0x59, 0x2c, 0x34, 0xaf, 0x39, 0xfe, 0x25, 0x7a, 0x0f, 0xd0, 0x7e, 0x4c, 0xe4, 0x96, 0xb4, 0x91,
	0x56, 0x92, 0x39, 0x98, 0xf7, 0x04, 0x1a, 0x0b, 0x0a, 0x57, 0x33, 0x11, 0x7f, 0x07, 0x6e, 0x04,
	0xf5, 0x05, 0x85, 0x4e, 0xdf, 0x7e, 0xb0, 0x42, 0x71, 0x73, 0xd2, 0x5b, 0x19, 0x11, 0x2e, 0xe1,
	0xc8, 0x55, 0x61, 0x3c, 0x17, 0x2f, 0x06, 0xfe, 0x63, 0xec, 0x2b, 0xbd, 0x73, 0x5a, 0x58, 0xf2,
	0x3a, 0x1d, 0x31, 0x8c, 0xe1, 0x38, 0x9f, 0xfe, 0x0f, 0x7f, 0x28, 0x2e, 0xed, 0x2b, 0x63, 0xc4,
	0xee, 0xcf, 0x97, 0x67, 0x07, 0x2f, 0x2b, 0xac, 0xb9, 0x63, 0xba, 0xfb, 0x0c, 0x00, 0x00, 0xff,
	0xff, 0xf1, 0x14, 0x59, 0x6b, 0x81, 0x02, 0x00, 0x00,
}
