# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import notifications_pb2 as notifications__pb2


class NotificationsServiceStub(object):
    """Definisi layanan gRPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FruitsNotifications = channel.unary_stream(
                '/notifications.NotificationsService/FruitsNotifications',
                request_serializer=notifications__pb2.NotificationsRequest.SerializeToString,
                response_deserializer=notifications__pb2.FruitResponse.FromString,
                )
        self.UniversitiesNotifications = channel.unary_stream(
                '/notifications.NotificationsService/UniversitiesNotifications',
                request_serializer=notifications__pb2.NotificationsRequest.SerializeToString,
                response_deserializer=notifications__pb2.UniversitiesResponse.FromString,
                )


class NotificationsServiceServicer(object):
    """Definisi layanan gRPC
    """

    def FruitsNotifications(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UniversitiesNotifications(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FruitsNotifications': grpc.unary_stream_rpc_method_handler(
                    servicer.FruitsNotifications,
                    request_deserializer=notifications__pb2.NotificationsRequest.FromString,
                    response_serializer=notifications__pb2.FruitResponse.SerializeToString,
            ),
            'UniversitiesNotifications': grpc.unary_stream_rpc_method_handler(
                    servicer.UniversitiesNotifications,
                    request_deserializer=notifications__pb2.NotificationsRequest.FromString,
                    response_serializer=notifications__pb2.UniversitiesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'notifications.NotificationsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NotificationsService(object):
    """Definisi layanan gRPC
    """

    @staticmethod
    def FruitsNotifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/notifications.NotificationsService/FruitsNotifications',
            notifications__pb2.NotificationsRequest.SerializeToString,
            notifications__pb2.FruitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UniversitiesNotifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/notifications.NotificationsService/UniversitiesNotifications',
            notifications__pb2.NotificationsRequest.SerializeToString,
            notifications__pb2.UniversitiesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
