# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifications.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13notifications.proto\x12\rnotifications\"1\n\x14NotificationsRequest\x12\x19\n\x11Notification_Name\x18\x01 \x01(\t\"s\n\rFruitResponse\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x10\n\x08\x43\x61lories\x18\x02 \x01(\x02\x12\x15\n\rCarbohydrates\x18\x03 \x01(\x02\x12\x0b\n\x03\x46\x61t\x18\x04 \x01(\x02\x12\x0f\n\x07Protein\x18\x05 \x01(\x02\x12\r\n\x05Sugar\x18\x06 \x01(\x02\"7\n\x14UniversitiesResponse\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x11\n\tWeb_Pages\x18\x02 \x01(\t2\xdb\x01\n\x14NotificationsService\x12Z\n\x13\x46ruitsNotifications\x12#.notifications.NotificationsRequest\x1a\x1c.notifications.FruitResponse0\x01\x12g\n\x19UniversitiesNotifications\x12#.notifications.NotificationsRequest\x1a#.notifications.UniversitiesResponse0\x01\x42\x1fZ\x1dpush_notifications/rpc-streamb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notifications_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035push_notifications/rpc-stream'
  _globals['_NOTIFICATIONSREQUEST']._serialized_start=38
  _globals['_NOTIFICATIONSREQUEST']._serialized_end=87
  _globals['_FRUITRESPONSE']._serialized_start=89
  _globals['_FRUITRESPONSE']._serialized_end=204
  _globals['_UNIVERSITIESRESPONSE']._serialized_start=206
  _globals['_UNIVERSITIESRESPONSE']._serialized_end=261
  _globals['_NOTIFICATIONSSERVICE']._serialized_start=264
  _globals['_NOTIFICATIONSSERVICE']._serialized_end=483
# @@protoc_insertion_point(module_scope)
